{* vim: set ts=2 sw=2 sts=2 et: *}

{**
 * Authorize.Net SIM configuration page
  *
   * @author    Creative Development LLC <info@cdev.ru>
    * @copyright Copyright (c) 2011-2012 Creative Development LLC <info@cdev.ru>. All rights reserved
     * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
      * @link      http://www.litecommerce.com/
       *}
       
       <table cellspacing="1" cellpadding="5" class="settings-table">
       
          <tr>
              <td class="setting-name">
                  <label for="settings_enabled">Enabled</label>
                      </td>
                          <td>
                              <select id="settings_test" name="settings[enabled]">
                                    <option value="1" selected="{isSelected(paymentMethod.getSetting(#enabled#),#1#)}">Yes</option>
                                          <option value="0" selected="{isSelected(paymentMethod.getSetting(#enabled#),#0#)}">No</option>
                                              </select>
                                                  </td>
                                                    </tr>  
                                                      
                                                        <tr>
                                                            <td class="setting-name">
                                                                <label for="settings_merchantid">MerchantId</label>
                                                                    </td>
                                                                        <td>
                                                                            <input type="text" id="settings_merchantid" name="settings[merchantid]" value="{paymentMethod.getSetting(#merchantid#)}"/>
                                                                                </td>
                                                                                  </tr>
                                                                                  
                                                                                     <tr>
                                                                                         <td class="setting-name">
                                                                                             <label for="settings_hmac">HMAC Key</label>
                                                                                                 </td>
                                                                                                     <td>
                                                                                                         <input type="text" id="settings_hmac" name="settings[hmac]" value="{paymentMethod.getSetting(#hmac#)}"/>
                                                                                                             </td>
                                                                                                               </tr>
                                                                                                                 
                                                                                                                      <tr>
                                                                                                                          <td class="setting-name">
                                                                                                                              <label for="settings_test">Test mode</label>
                                                                                                                                  </td>
                                                                                                                                      <td>
                                                                                                                                          <select id="settings_test" name="settings[test]">
                                                                                                                                                <option value="1" selected="{isSelected(paymentMethod.getSetting(#test#),#1#)}">Yes</option>
                                                                                                                                                      <option value="0" selected="{isSelected(paymentMethod.getSetting(#test#),#0#)}">No</option>
                                                                                                                                                          </select>
                                                                                                                                                              </td>
                                                                                                                                                                </tr>  
                                                                                                                                                                  
                                                                                                                                                                       <tr>
                                                                                                                                                                           <td class="setting-name">
                                                                                                                                                                               <label for="settings_addfee">Add fee</label>
                                                                                                                                                                                   </td>
                                                                                                                                                                                       <td>
                                                                                                                                                                                           <select id="settings_addfee" name="settings[addfee]">
                                                                                                                                                                                                 <option value="1" selected="{isSelected(paymentMethod.getSetting(#addfee#),#1#)}">Yes</option>
                                                                                                                                                                                                       <option value="0" selected="{isSelected(paymentMethod.getSetting(#addfee#),#0#)}">No</option>
                                                                                                                                                                                                           </select>
                                                                                                                                                                                                               </td>
                                                                                                                                                                                                                 </tr>  
                                                                                                                                                                                                                   
                                                                                                                                                                                                                     <tr>
                                                                                                                                                                                                                         <td class="setting-name">
                                                                                                                                                                                                                             <label for="settings_capturenow">Capure now</label>
                                                                                                                                                                                                                                 </td>
                                                                                                                                                                                                                                     <td>
                                                                                                                                                                                                                                         <select id="settings_capturenow" name="settings[capturenow]">
                                                                                                                                                                                                                                               <option value="1" selected="{isSelected(paymentMethod.getSetting(#capturenow#),#1#)}">Yes</option>
                                                                                                                                                                                                                                                     <option value="0" selected="{isSelected(paymentMethod.getSetting(#capturenow#),#0#)}">No</option>
                                                                                                                                                                                                                                                         </select>
                                                                                                                                                                                                                                                             </td>
                                                                                                                                                                                                                                                               </tr>  
                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                   <tr>
                                                                                                                                                                                                                                                                       <td class="setting-name">
                                                                                                                                                                                                                                                                           <label for="settings_paytype">Paytype</label>
                                                                                                                                                                                                                                                                               </td>
                                                                                                                                                                                                                                                                                   <td>
                                                                                                                                                                                                                                                                                       <input type="text" id="settings_paytype" name="settings[paytype]" value="{paymentMethod.getSetting(#paytype#)}"/>
                                                                                                                                                                                                                                                                                           </td>
                                                                                                                                                                                                                                                                                             </tr>
                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                 <tr>
                                                                                                                                                                                                                                                                                                     <td class="setting-name">
                                                                                                                                                                                                                                                                                                         <label for="settings_language">Language</label>
                                                                                                                                                                                                                                                                                                             </td>
                                                                                                                                                                                                                                                                                                                 <td>
                                                                                                                                                                                                                                                                                                                     <select id="settings_language" name="settings[language]">
                                                                                                                                                                                                                                                                                                                           <option value="da_DK" selected="{isSelected(paymentMethod.getSetting(#languagew#),#da_DK#)}">Danish</option>
                                                                                                                                                                                                                                                                                                                                 <option value="en_UK" selected="{isSelected(paymentMethod.getSetting(#language#),#en_UK#)}">English</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <option value="nb_NO" selected="{isSelected(paymentMethod.getSetting(#language#),#nb_NO#)}">Norwegian</option>
                                                                                                                                                                                                                                                                                                                                                   <option value="sv_SE" selected="{isSelected(paymentMethod.getSetting(#language#),#sv_SE#)}">Swedish</option>
                                                                                                                                                                                                                                                                                                                                                       </select>
                                                                                                                                                                                                                                                                                                                                                           </td>
                                                                                                                                                                                                                                                                                                                                                             </tr> 
                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                 <tr>
                                                                                                                                                                                                                                                                                                                                                                     <td class="setting-name">
                                                                                                                                                                                                                                                                                                                                                                         <label for="settings_account">Account</label>
                                                                                                                                                                                                                                                                                                                                                                             </td>
                                                                                                                                                                                                                                                                                                                                                                                 <td>
                                                                                                                                                                                                                                                                                                                                                                                     <input type="text" id="settings_account" name="settings[account]" value="{paymentMethod.getSetting(#account#)}"/>
                                                                                                                                                                                                                                                                                                                                                                                         </td>
                                                                                                                                                                                                                                                                                                                                                                                           </tr>
                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                           </table>
                                                                                                                                                                                                                                                                                                                                                                                           